### ISSUE TITLE
关于您储存库涉及重庆农商银行的问题沟通

### ISSUE THREAD

**Issue by yeeton-bj** [CxsGhost/DataScience_ML_DL#1]
您好，
我们是重庆农商银行股份有限公司提供安全服务的厂商-北京亿盾互联科技有限公司。受重庆农商委托，跟您沟通有关重庆农商的问题。经银行技术部门反馈，您在github上发布的以下1个链接中的内容涉及重庆农商的关键字或内部代码，现在重庆农商进行护网行动需要删除银行关键信息。请麻烦您删除下此链接相关内容，谢谢配合！

 内容链接：
https://github.com/CxsGhost/DataScience_DL_ML_competitions

 内容截图：
![image](https://github.com/CxsGhost/DataScience_DL_ML_competitions/assets/90314410/99129da1-d3d0-4d73-8871-67c62a5bd9f4)

**Comment by CxsGhost** [comment]
这只是农商行先前对高校举办的比赛，里面只是我自己写的比赛相关代码而已，根本不存在也不涉及你们的内部代码，请搞清楚。由于使用了你们的名字，我会对此目录改名，但其下内容是我个人知识产权，你无权要求我删除。
